# Generated by Django 4.0.5 on 2023-02-27 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alias', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alias',
            name='links',
            field=models.ManyToManyField(to='alias.links'),
        ),
    ]
