from .commons import *
import os


DATABASE_NAME = os.getenv("DATABASE_NAME")
DATABASE_URL = os.getenv("DATABASE_URL")
DATABASE_PORT = os.getenv("DATABASE_PORT")
DATABASE_USER = os.getenv("DATABASE_USER")
DATABASE_PASSWORD = os.getenv("DATABASE_PASSWORD")


SECRET_KEY = os.getenv("SECRET_KEY")
DEBUG = False
BROKER_SCHEMA = os.getenv("BROKER_SCHEMA")
BROKER_USER = os.getenv("BROKER_USER")
BROKER_PASSWORD = os.getenv("BROKER_PASSWORD")
BROKER_HOST = os.getenv("BROKER_HOST")
BROKER_PORT = os.getenv("BROKER_PORT")
CELERY_CACHE_BACKEND = "default"

CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_ENABLE_UTC = True

AMQP_BROKER_URL = (
    f"{BROKER_SCHEMA}://{BROKER_USER}:{BROKER_PASSWORD}@{BROKER_HOST}:{BROKER_PORT}/"
)
BROKER_URL = AMQP_BROKER_URL

DJANGO_CELERY_RESULTS_TASK_ID_MAX_LENGTH = 191
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": DATABASE_NAME,
        "USER": DATABASE_USER,
        "PASSWORD": DATABASE_PASSWORD,
        "HOST": DATABASE_URL,
        "PORT": DATABASE_PORT,
    }
}
